// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One increment of an answer stream — cairn's own closed wire vocabulary,
 * mirroring `cairn_ports::AgentEvent` plus a leading `Sources` frame. Struct
 * variants are required: `#[serde(tag = "type")]` cannot tag a newtype variant.
 */
export type AnswerEvent = { "type": "sources", 
/**
 * Relative note paths, in rank order.
 */
paths: Array<string>, } | { "type": "text_delta", 
/**
 * The text fragment.
 */
text: string, } | { "type": "tool_started", 
/**
 * Tool name.
 */
tool: string, } | { "type": "tool_completed", 
/**
 * Tool name.
 */
tool: string, 
/**
 * Whether the call succeeded.
 */
ok: boolean, } | { "type": "turn_completed" } | { "type": "completed" } | { "type": "failed", 
/**
 * Failure detail.
 */
message: string, };
