// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A streaming, note-grounded question. Its own shape — not a `Command` (no
 * mutation) and not a `Query` (no single response).
 */
export type AskRequest = { 
/**
 * The question to answer.
 */
query: string, 
/**
 * How many top search hits to ground the answer in. `None` ⇒ 5.
 */
top_k: number | null, };
