// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a commit changed, in note terms (engine-computed).
 */
export type ChangeSummary = { 
/**
 * Number of files touched.
 */
files_changed: number, 
/**
 * Unicode-whitespace-split words added.
 */
words_added: number, 
/**
 * Unicode-whitespace-split words removed.
 */
words_removed: number, };
