// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireBlockOp } from "./WireBlockOp";

/**
 * Messages the daemon sends to a collaboration client over `/collab`.
 */
export type CollabServerMsg = { "type": "joined", note: string, } | { "type": "snapshot", note: string, ops: Array<WireBlockOp>, } | { "type": "op", note: string, op: WireBlockOp, } | { "type": "error", note: string, message: string, };
