// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireBlockId } from "./WireBlockId";
import type { WireBlockOp } from "./WireBlockOp";

/**
 * Messages a collaboration client sends to the daemon over `/collab`.
 */
export type CollabClientMsg = { "type": "join", note: string, replica: bigint, } | { "type": "op", note: string, op: WireBlockOp, } | { "type": "leave", note: string, } | { "type": "recover", note: string, } | { "type": "restore", note: string, id: WireBlockId, version_index: number, };
