// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Result of a successful command.
 */
export type CommandResponse = { "type": "done" } | { "type": "committed", 
/**
 * Short commit id.
 */
commit: string, } | { "type": "plugin_result", 
/**
 * The command's JSON output.
 */
result: JsonValue, };
