// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A request that mutates the cairn.
 */
export type Command = { "type": "write_note", 
/**
 * Relative note path.
 */
path: string, 
/**
 * Full markdown contents.
 */
contents: string, } | { "type": "delete_note", 
/**
 * Relative note path.
 */
path: string, } | { "type": "commit", 
/**
 * Commit message.
 */
message: string, };
