// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a successful command.
 */
export type CommandResponse = { "type": "done" } | { "type": "committed", 
/**
 * Short commit id.
 */
commit: string, };
