// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed error returned across the contract boundary.
 */
export type ContractError = { "type": "not_found", 
/**
 * What was missing (e.g. a note path).
 */
what: string, } | { "type": "invalid_request", 
/**
 * Human-readable reason.
 */
message: string, } | { "type": "internal", 
/**
 * Human-readable detail.
 */
message: string, };
