// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A push event emitted by the engine.
 */
export type Event = { "type": "note_changed", 
/**
 * Relative note path.
 */
path: string, } | { "type": "note_deleted", 
/**
 * Relative note path.
 */
path: string, } | { "type": "committed", 
/**
 * Short commit id.
 */
commit: string, } | { "type": "reindexed", 
/**
 * Number of notes indexed.
 */
count: number, };
