// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A directed link edge between two notes, by path.
 */
export type GraphEdge = { 
/**
 * Source note path.
 */
from: string, 
/**
 * Target note path.
 */
to: string, };
