// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which slice of the graph to return.
 */
export type GraphScope = { "type": "full" } | { "type": "focused", 
/**
 * Focus note path.
 */
path: string, 
/**
 * Hop radius.
 */
depth: number, };
