// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node in the link graph: a note plus light display metadata.
 */
export type GraphNode = { 
/**
 * Relative note path.
 */
path: string, 
/**
 * Display title at this revision (frontmatter `title:` → first `# ` → stem).
 */
title: string, 
/**
 * Last-modified, Unix seconds. HEAD: filesystem mtime. Historical: newest
 * commit ≤ the revision that touched the note.
 */
mtime_secs: bigint, };
