// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note's path and display title, for list views.
 */
export type NoteSummary = { 
/**
 * Relative note path.
 */
path: string, 
/**
 * Display title (frontmatter title, first heading, or filename).
 */
title: string, 
/**
 * Frontmatter tags of the note.
 */
tags: Array<string>, };
