// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginCommandSummary } from "./PluginCommandSummary";

/**
 * A loaded plugin and its commands (response to `ListPlugins`).
 */
export type PluginSummary = { 
/**
 * Manifest id.
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Version.
 */
version: string, 
/**
 * Declared commands.
 */
commands: Array<PluginCommandSummary>, };
