// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An icon a plugin may reference by name. Closed set — never a string/URL/SVG.
 */
export type PluginIcon = "tag" | "search" | "note" | "folder" | "link" | "star" | "info" | "play";
