// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A capability a Tier-3 (sandboxed-iframe) plugin may request.
 */
export type PluginCapability = "activeNote.read" | "activeNote.write" | "notes.read" | "notes.search" | "command.invoke";
