// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginIcon } from "./PluginIcon";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One row inside a `list` widget.
 */
export type PluginListItem = { id: string, label: string, icon: PluginIcon | null, command: string | null, args: JsonValue | null, };
