// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginCapability } from "./PluginCapability";
import type { PluginCommandSummary } from "./PluginCommandSummary";
import type { PluginContribution } from "./PluginContribution";

/**
 * A loaded plugin and its commands (response to `ListPlugins`).
 */
export type PluginSummary = { 
/**
 * Manifest id.
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Version.
 */
version: string, 
/**
 * Declared commands.
 */
commands: Array<PluginCommandSummary>, 
/**
 * UI contributions (Tier-2). Empty for plugins that declare none.
 */
contributions: Array<PluginContribution>, 
/**
 * Capabilities a Tier-3 plugin requests. None for plugins that declare none.
 */
capabilities?: Array<PluginCapability> | null, 
/**
 * Root directory of the plugin's UI bundle (Tier-3). None if it declares no UI.
 */
uiRoot?: string | null, };
