// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginIcon } from "./PluginIcon";
import type { PluginSlot } from "./PluginSlot";
import type { PluginWidget } from "./PluginWidget";

/**
 * One placement of one widget into one slot.
 */
export type PluginContribution = { id: string, slot: PluginSlot, widget: PluginWidget, title: string | null, icon: PluginIcon | null, order: number | null, };
