// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginIcon } from "./PluginIcon";
import type { PluginListItem } from "./PluginListItem";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A host-renderable widget. Closed vocabulary; first cut: text / action / list.
 */
export type PluginWidget = { "kind": "text", text: string, muted: boolean | null, } | { "kind": "action", label: string, icon: PluginIcon | null, command: string, args: JsonValue | null, } | { "kind": "list", items: Array<PluginListItem>, };
