// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command a plugin handles.
 */
export type PluginCommandSummary = { 
/**
 * Command id.
 */
id: string, 
/**
 * Human title.
 */
title: string, };
