// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphScope } from "./GraphScope";
import type { SuggestionScope } from "./SuggestionScope";

/**
 * A read-only request.
 */
export type Query = { "type": "get_note", 
/**
 * Relative note path.
 */
path: string, } | { "type": "search", 
/**
 * Query string.
 */
query: string, } | { "type": "get_backlinks", 
/**
 * Relative note path.
 */
path: string, } | { "type": "list_notes" } | { "type": "get_graph", 
/**
 * Which slice to return.
 */
scope: GraphScope, } | { "type": "graph_at", 
/**
 * A git revspec (short/full hash, `HEAD~1`…).
 */
revision: string, 
/**
 * Which slice to return.
 */
scope: GraphScope, } | { "type": "graph_diff", 
/**
 * Older revspec.
 */
from: string, 
/**
 * Newer revspec.
 */
to: string, 
/**
 * Which slice to diff.
 */
scope: GraphScope, } | { "type": "list_tags" } | { "type": "notes_by_tag", 
/**
 * The tag to filter by.
 */
tag: string, } | { "type": "get_suggestions", 
/**
 * What to compute suggestions over.
 */
scope: SuggestionScope, } | { "type": "list_plugins" } | { "type": "note_history", 
/**
 * Relative note path.
 */
path: string, } | { "type": "note_at", 
/**
 * Relative note path.
 */
path: string, 
/**
 * A git revspec (short/full hash, `HEAD~1`…).
 */
revision: string, };
