// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { NoteSummary } from "./NoteSummary";

/**
 * Result of a successful query.
 */
export type QueryResponse = { "type": "note", 
/**
 * Full markdown contents.
 */
contents: string, } | { "type": "paths", 
/**
 * Relative note paths.
 */
paths: Array<string>, } | { "type": "notes", 
/**
 * One per note.
 */
notes: Array<NoteSummary>, } | { "type": "graph", 
/**
 * All note paths.
 */
nodes: Array<string>, 
/**
 * Directed link edges.
 */
edges: Array<GraphEdge>, };
