// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A read-only request.
 */
export type Query = { "type": "get_note", 
/**
 * Relative note path.
 */
path: string, } | { "type": "search", 
/**
 * Query string.
 */
query: string, } | { "type": "get_backlinks", 
/**
 * Relative note path.
 */
path: string, };
