// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";
import type { NoteSummary } from "./NoteSummary";
import type { PluginSummary } from "./PluginSummary";
import type { Revision } from "./Revision";
import type { SearchResult } from "./SearchResult";
import type { SuggestedEdge } from "./SuggestedEdge";
import type { TagCount } from "./TagCount";

/**
 * Result of a successful query.
 */
export type QueryResponse = { "type": "note", 
/**
 * Full markdown contents.
 */
contents: string, } | { "type": "paths", 
/**
 * Relative note paths.
 */
paths: Array<string>, } | { "type": "search_results", 
/**
 * Best match first.
 */
results: Array<SearchResult>, } | { "type": "notes", 
/**
 * One per note.
 */
notes: Array<NoteSummary>, } | { "type": "graph", 
/**
 * Enriched nodes.
 */
nodes: Array<GraphNode>, 
/**
 * Directed link edges.
 */
edges: Array<GraphEdge>, } | { "type": "graph_diff", 
/**
 * Nodes present in `to` not `from`.
 */
nodes_added: Array<GraphNode>, 
/**
 * Nodes present in `from` not `to`.
 */
nodes_removed: Array<GraphNode>, 
/**
 * Edges present in `to` not `from`.
 */
edges_added: Array<GraphEdge>, 
/**
 * Edges present in `from` not `to`.
 */
edges_removed: Array<GraphEdge>, } | { "type": "tags", 
/**
 * One per distinct tag, sorted by tag.
 */
tags: Array<TagCount>, } | { "type": "plugins", 
/**
 * One per loaded plugin.
 */
plugins: Array<PluginSummary>, } | { "type": "history", 
/**
 * One per commit, newest first.
 */
revisions: Array<Revision>, } | { "type": "suggestions", 
/**
 * Best match first.
 */
suggestions: Array<SuggestedEdge>, };
