// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit in a note's history (response element of `NoteHistory`).
 */
export type Revision = { 
/**
 * Short commit id.
 */
id: string, 
/**
 * Commit summary (first line).
 */
message: string, 
/**
 * Commit time, seconds since the Unix epoch.
 */
timestamp_secs: bigint, 
/**
 * Author name.
 */
author: string, };
