// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked search result.
 */
export type SearchResult = { 
/**
 * Relative note path.
 */
path: string, 
/**
 * Relevance score (relative ordering only).
 */
score: number, 
/**
 * Plain-text excerpt around the match.
 */
snippet: string, 
/**
 * `(start, end)` byte ranges within `snippet` that matched.
 */
highlights: Array<[number, number]>, };
