// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A suggested, non-explicit edge between two notes by path. `weight` is a
 * similarity *ranking* in `0..1`, not a plottable distance.
 */
export type SuggestedEdge = { 
/**
 * Source note path.
 */
from: string, 
/**
 * Target note path.
 */
to: string, 
/**
 * Cosine similarity, `0..1`. Relative ordering only.
 */
weight: number, 
/**
 * Human-readable provenance, e.g. `"shared: ownership, borrow"`. `None` if unknown.
 */
why: string | null, };
