// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a `GetSuggestions` query computes suggestions over.
 */
export type SuggestionScope = { "type": "note", 
/**
 * Relative note path.
 */
path: string, } | { "type": "vault" };
