// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tag and how many notes carry it.
 */
export type TagCount = { 
/**
 * The tag.
 */
tag: string, 
/**
 * Number of notes carrying it.
 */
count: number, };
