// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireAuthor } from "./WireAuthor";
import type { WireBlockId } from "./WireBlockId";
import type { WireBlockKind } from "./WireBlockKind";

/**
 * A replicated block operation on the wire (mirror of `cairn-domain`
 * `BlockOp`). The only CRDT type carried by `/collab`.
 */
export type WireBlockOp = { "op": "insert", id: WireBlockId, after: WireBlockId | null, 
/**
 * Lamport clock. String-encoded (unbounded u64). See `u64_string`.
 */
lamport: string, kind: WireBlockKind, text: string, } | { "op": "delete", id: WireBlockId, 
/**
 * Lamport clock. String-encoded (unbounded u64). See `u64_string`.
 */
lamport: string, } | { "op": "set_content", id: WireBlockId, text: string, 
/**
 * Lamport clock. String-encoded (unbounded u64). See `u64_string`.
 */
lamport: string, author: WireAuthor, };
