// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Block taxonomy (wire mirror of `cairn-domain` `BlockKind`).
 */
export type WireBlockKind = "frontmatter" | "heading" | "paragraph" | "list_item" | "code_fence" | "block_quote" | "table" | "thematic_break";
