// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A block's live-only identity, mirrored for the wire. See `cairn-domain`
 * `BlockId`. Stripped on materialize; meaningful only within a live session.
 */
export type WireBlockId = { replica: bigint, counter: bigint, };
