// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who authored an edit (wire mirror of `cairn-domain` `Author`).
 */
export type WireAuthor = "human" | "agent";
