// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A block's live-only identity, mirrored for the wire. See `cairn-domain`
 * `BlockId`. Stripped on materialize; meaningful only within a live session.
 */
export type WireBlockId = { 
/**
 * Authoring replica id. String-encoded — reaches `u64::MAX`. See `u64_string`.
 */
replica: string, 
/**
 * Per-replica monotonic counter. String-encoded. See `u64_string`.
 */
counter: string, };
