// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireBlockId } from "./WireBlockId";

/**
 * One block's recoverable content on the wire (mirror of `cairn-domain`
 * `RecoverableBlock`). `id` is the shared live-only block id, so a joined
 * client correlates it with blocks it already knows.
 */
export type WireRecoverableBlock = { id: WireBlockId, tombstoned: boolean, versions: Array<string>, };
