// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireAuthor } from "./WireAuthor";
import type { WireBlockId } from "./WireBlockId";
import type { WireBlockKind } from "./WireBlockKind";

/**
 * A replicated block operation on the wire (mirror of `cairn-domain`
 * `BlockOp`). The only CRDT type carried by `/collab`.
 */
export type WireBlockOp = { "op": "insert", id: WireBlockId, after: WireBlockId | null, lamport: bigint, kind: WireBlockKind, text: string, } | { "op": "delete", id: WireBlockId, lamport: bigint, } | { "op": "set_content", id: WireBlockId, text: string, lamport: bigint, author: WireAuthor, };
