#!/usr/bin/env bash
# Vendor the generated TS contract from the cairn engine repo.
# Usage: scripts/sync-contract.sh [path-to-cairn-repo]  (default: ../cairn)
set -euo pipefail
SRC="${1:-../cairn}"
BINDINGS="$SRC/crates/cairn-contract/bindings"
DEST="web/src/contract"

[ -d "$BINDINGS" ] || { echo "bindings not found at $BINDINGS"; exit 1; }
cp "$BINDINGS/Command.ts" "$BINDINGS/Query.ts" "$BINDINGS/Event.ts" "$DEST/"

COMMIT="$(git -C "$SRC" rev-parse HEAD)"
cat > "$DEST/source.ts" <<EOF
// Generated by scripts/sync-contract.sh — do not edit by hand.
export const CONTRACT_SOURCE_COMMIT = "$COMMIT";
EOF
echo "synced contract from $SRC @ $COMMIT"
