#!/usr/bin/env bash
# Vendor the generated TS contract from the cairn engine repo.
# Usage: scripts/sync-contract.sh [path-to-cairn-repo]  (default: ../cairn)
set -euo pipefail
SRC="${1:-../cairn}"
BINDINGS="$SRC/crates/cairn-contract/bindings"
DEST="web/src/contract"

[ -d "$BINDINGS" ] || { echo "bindings not found at $BINDINGS"; exit 1; }
mkdir -p "$DEST"
# Copy every generated binding (the set grows as the contract evolves).
cp "$BINDINGS"/*.ts "$DEST/"
# Copy nested bindings too (e.g. serde_json/JsonValue.ts referenced by
# Command/CommandResponse). The set of subdirs grows as the contract evolves.
find "$BINDINGS" -mindepth 1 -type d | while read -r dir; do
  rel="${dir#"$BINDINGS"/}"
  mkdir -p "$DEST/$rel"
  cp "$dir"/*.ts "$DEST/$rel/"
done

COMMIT="$(git -C "$SRC" rev-parse HEAD)"
cat > "$DEST/source.ts" <<EOF
// Generated by scripts/sync-contract.sh — do not edit by hand.
export const CONTRACT_SOURCE_COMMIT = "$COMMIT";
EOF

# The vendored copy is committed verbatim in ts-rs' own output format — it is
# NOT reformatted to the repo's prettier style. web/src/contract is listed in
# web/.prettierignore so the gate (format:check) and `just fix` leave it alone;
# the DX3 drift check (scripts/check-contract-drift.sh) re-runs this script and
# compares byte-for-byte, so any normalization here would have to match ts-rs
# exactly — simpler to keep both sides raw.

echo "synced contract from $SRC @ $COMMIT"
