#!/usr/bin/env bash
# Vendor the generated TS contract from the cairn engine repo.
# Usage: scripts/sync-contract.sh [path-to-cairn-repo]  (default: ../cairn)
set -euo pipefail
SRC="${1:-../cairn}"
BINDINGS="$SRC/crates/cairn-contract/bindings"
DEST="web/src/contract"

[ -d "$BINDINGS" ] || { echo "bindings not found at $BINDINGS"; exit 1; }
mkdir -p "$DEST"
# Copy every generated binding (the set grows as the contract evolves).
cp "$BINDINGS"/*.ts "$DEST/"
# Copy nested bindings too (e.g. serde_json/JsonValue.ts referenced by
# Command/CommandResponse). The set of subdirs grows as the contract evolves.
find "$BINDINGS" -mindepth 1 -type d | while read -r dir; do
  rel="${dir#"$BINDINGS"/}"
  mkdir -p "$DEST/$rel"
  cp "$dir"/*.ts "$DEST/$rel/"
done

COMMIT="$(git -C "$SRC" rev-parse HEAD)"
cat > "$DEST/source.ts" <<EOF
// Generated by scripts/sync-contract.sh — do not edit by hand.
export const CONTRACT_SOURCE_COMMIT = "$COMMIT";
EOF

# Normalize to the repo's prettier style: the vendored copy is committed
# formatted, but ts-rs emits unformatted output. Without this the copy would
# "drift" from itself on every sync (and the DX3 drift check would never pass).
( cd web && pnpm exec prettier --log-level warn --write "src/contract/**/*.ts" )

echo "synced contract from $SRC @ $COMMIT"
